<a href="https://colab.research.google.com/github/andresit02/Examen-II-BIMESTRE/blob/main/Sistemas_de_Ecuaciones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
%load_ext autoreload
# %autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


****Método de Gauss - Jordan****

In [51]:
# ####################################################################
def gauss_jordan(Ab: np.ndarray) -> np.ndarray:
    """Resuelve un sistema de ecuaciones lineales mediante el método de Gauss-Jordan.

    ## Parameters

    ``Ab``: matriz aumentada del sistema de ecuaciones lineales. Debe ser de tamaño n-by-(n+1), donde n es el número de incógnitas.

    ## Return

    ``solucion``: vector con la solución del sistema de ecuaciones lineales.

    """
    if not isinstance(Ab, np.ndarray):
        logging.debug("Convirtiendo A a numpy array.")
        Ab = np.array(Ab, dtype=float)
    assert Ab.shape[0] == Ab.shape[1] - 1, "La matriz A debe ser de tamaño n-by-(n+1)."
    n = Ab.shape[0]

    for i in range(0, n):  # loop por columna

        # --- encontrar pivote
        p = None  # default, first element
        for pi in range(i, n):
            if Ab[pi, i] == 0:
                # must be nonzero
                continue

            if p is None:
                # first nonzero element
                p = pi
                continue

            if abs(Ab[pi, i]) < abs(Ab[p, i]):
                p = pi

        if p is None:
            # no pivot found.
            raise ValueError("No existe solución única.")

        if p != i:
            # swap rows
            logging.debug(f"Intercambiando filas {i} y {p}")
            _aux = Ab[i, :].copy()
            Ab[i, :] = Ab[p, :].copy()
            Ab[p, :] = _aux

        # --- Eliminación: loop por fila
        for j in range(n):
            if i == j:
                continue
            m = Ab[j, i] / Ab[i, i]
            Ab[j, i:] = Ab[j, i:] - m * Ab[i, i:]

        logging.info(f"\n{Ab}")

    if Ab[n - 1, n - 1] == 0:
        raise ValueError("No existe solución única.")

    # --- Sustitución hacia atrás
    solucion = np.zeros(n)

    for i in range(n - 1, -1, -1):
        solucion[i] = Ab[i, -1] / Ab[i, i]

    return solucion

****Método para sacar la matriz inversa****

In [59]:
def inv_matrix(A: np.ndarray) -> np.ndarray:
    """
    Inversión de una matriz cuadrada mediante el método de Gauss-Jordan.

    ## Parameters
    ``A``: matriz cuadrada de tamaño n x n.

    ## Return
    ``A_inv``: matriz inversa de A.
    """
    assert A.shape[0] == A.shape[1], "La matriz debe ser cuadrada para calcular la inversa."
    n = A.shape[0]

    A_aug = np.concatenate((A.astype(float), np.identity(n)), axis=1)

    # Aplicación de la eliminación Gauss-Jordan
    for i in range(n):
        # Verificar si el pivote es cero
        if np.isclose(A_aug[i, i], 0):
            # Buscar una fila para intercambiar
            for k in range(i + 1, n):
                if not np.isclose(A_aug[k, i], 0):
                    # Intercambio de filas
                    A_aug[[i, k]] = A_aug[[k, i]]
                    break
            else:
                raise ValueError("La matriz es singular y no tiene inversa.")

        A_aug[i, :] /= A_aug[i, i]

        for j in range(n):
            if i != j:
                factor = A_aug[j, i]
                A_aug[j, :] -= factor * A_aug[i, :]

    A_inv = A_aug[:, n:]
    return A_inv

****Ejemplo 1****

In [60]:
import numpy as np

# Defino la matriz
A = np.array([
    [1, 2, 3, 4],
    [2, 5, 6, 7],
    [3, 6, 8, 9],
    [4, 7, 9, 10]
], dtype=float)

# Calculo la inversa
try:
    A_inv = inv_matrix(A)
    print(A_inv)
except ValueError as e:
    print(f"Error: {e}")

[[ 0.5 -0.5 -1.5  1.5]
 [-0.5  1.5 -1.5  0.5]
 [-1.5 -1.5  3.5 -1.5]
 [ 1.5  0.5 -1.5  0.5]]


****Ejemplo 2****

In [61]:
import numpy as np

# Defino la matriz
A = np.array([
    [4, 4, 5, 1],
    [3, 4, 2, 2],
    [2, 1, 4, 1],
    [3, 2, 5, 4]
], dtype=float)

# Calculo la inversa
try:
    A_inv = inv_matrix(A)
    print(A_inv)
except ValueError as e:
    print(f"Error: {e}")

[[-34.  31.  52. -20.]
 [ 19. -17. -29.  11.]
 [ 12. -11. -18.   7.]
 [  1.  -1.  -2.   1.]]


****Ejercicio 1****

In [62]:
import numpy as np

# Defino la matriz
A = np.array([
    [2, -3],
    [-1, 1]
], dtype=float)

# Calculo la inversa
try:
    A_inv = inv_matrix(A)
    print(A_inv)
except ValueError as e:
    print(f"Error: {e}")

[[-1. -3.]
 [-1. -2.]]


****Ejercicio 2****

In [63]:
import numpy as np

# Defino la matriz
A = np.array([
    [4, 0, 0, 5],
    [1, 0, 4, 0],
    [3, 4, 1, 3],
    [1, 3, 3, 0]
], dtype=float)

# Calculo la inversa
try:
    A_inv = inv_matrix(A)
    print(A_inv)
except ValueError as e:
    print(f"Error: {e}")

[[-36.  45.  60. -80.]
 [  3.  -4.  -5.   7.]
 [  9. -11. -15.  20.]
 [ 29. -36. -48.  64.]]


****Ejercicio 3****

In [64]:
import numpy as np

# Defino la matriz
A = np.array([
    [0, 0, 0, 0, 0, 0, 1, -1],
    [0, 1, -1, 1, 0, -1, 0, 1],
    [-1, -1, 0, 0, 2, 1, 0, 0],
    [-1, -1, -1, 1, 2, 0, 0, 1],
    [-1, 1, 1, 0, -1, -1, 0, 2],
    [0, 1, 0, 0, -1, -1, 0, 0],
    [1, -1, -1, 1, 2, 1, 0, 2],
    [2, 0, 0, 0, 0, 1, 2, 0]
], dtype=float)

# Calculo la inversa
try:
    A_inv = inv_matrix(A)
    print(A_inv)
except ValueError as e:
    print(f"Error: {e}")

[[ 2. -1.  0. -1.  0.  2.  2. -1.]
 [ 0.  1.  1. -1.  0.  0.  0.  0.]
 [ 6. -1.  0. -3.  1.  1.  4. -3.]
 [ 6.  1. -1. -3.  1. -3.  3. -3.]
 [ 2. -1.  1. -1.  0.  3.  2. -1.]
 [-2.  2.  0.  0.  0. -4. -2.  1.]
 [-1.  0.  0.  1.  0.  0. -1.  1.]
 [-2.  0.  0.  1.  0.  0. -1.  1.]]


****Ejercicio 4****

In [66]:
import numpy as np

# Defino la matriz
A = np.array([
    [1, 0, 0, 0, -1, 0, 0, -1, 1, -1],
    [1, 1, 0, -1, -1, 1, 0, 0, 1, -1],
    [-1, 0, -1, 0, 0, 0, -1, 1, 0, 0],
    [0, 0, -1, 0, -1, -1, 1, 0, 1, 0],
    [-1, 0, 0, -1, 1, 1, 1, 1, 0, -1],
    [1, 0, 0, 1, -1, -1, -1, 1, -1, 0],
    [1, 1, 1, 0, 1, 0, -1, -1, -1, 1],
    [1, 1, 1, 1, 0, 0, 1, 1, 0, 0],
    [1, 1, 1, 1, 1, 0, -1, -1, 0, 0],
    [0, 0, -1, -1, -1, 0, 1, 1, 1, -1]
], dtype=float)

# Calculo la inversa
try:
    A_inv = inv_matrix(A)
    print(A_inv)
except ValueError as e:
    print(f"Error: {e}")

[[ 14.  -8.   9.  -4.   0.  -4.   9.   7.  -8.   3.]
 [ -2.   2.  -1.   2.   1.   1.  -1.  -1.   1.  -2.]
 [-27.  14. -18.   5.  -2.   7. -17. -13.  16.  -2.]
 [ 12.  -6.   8.  -2.   1.  -3.   7.   6.  -7.   0.]
 [  6.  -4.   4.  -2.   0.  -2.   4.   3.  -3.   2.]
 [ 18.  -9.  12.  -4.   1.  -5.  11.   9. -11.   1.]
 [  8.  -4.   5.  -1.   1.  -2.   5.   4.  -5.   0.]
 [ -5.   2.  -3.   0.  -1.   1.  -3.  -2.   3.   1.]
 [-11.   5.  -7.   1.  -2.   2.  -7.  -5.   7.   1.]
 [  1.  -1.   1.  -1.  -1.  -1.   1.   1.  -1.   1.]]
